### ISSUE TITLE
multiple lisences files

### ISSUE THREAD

**Issue by solomoncyj** [mkrueger/icy_sixel#4]
hey, some of the lisence files you used linkes to non exsistet files on your project. can you please clarify which SPDX lisence your project is under?

**Comment by mkrueger** [comment]
I really need email notification for icy_sixel issues.

Sure - updated. It's MIT-X11 or Apache 2.0 as all my projects are. Libsixel is MIT-X11 the other licenses were for demos and images - which I don't translate/ship.
